name: lighthouse ci

on: [push, workflow_dispatch]

jobs:
  lighthouseci:
    runs-on: f64s
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install && npm install -g @lhci/cli@0.4.x
      - run: npm run site
      - run: lhci autorun --upload.target=temporary-public-storage
