name: lighthouse ci

on: [push, workflow_dispatch]

jobs:
  lighthouseci:
    continue-on-error: true
    runs-on: ${{ matrix.runner_type }}
    strategy:
      matrix:
        runner_type: [ds2v2,ds2v3,d2dsv4,d2asv4,d4asv4,ds3v2,ds4v2,ds5v2,f4s,f8s,f16s,f32s] 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: |
          sudo apt --fix-broken install -y
      - run: npm install && npm install -g @lhci/cli@0.4.x
      - run: npm run site
      - run: lhci autorun --upload.target=temporary-public-storage
